Add AOCODARCF4V3
aocodarc/inav pull request #1
Opened 2023-11-22 09:02 UTC by 634296207

Add AOCODARCF4V3

2023-11-22 11:22 UTC, aocodarc commented
a) OK, we use AOCODARCF4V3 for the target, keep format consisitency with F4V2
b) Please do self test. Make sure self-test is passed, and add comment below

```
F405V3 Flash V2 self test passed.
```

2023-11-22 11:28 UTC, lida2003 commented on src/main/target/AOCODARCF4V3/target.h
> +#define PINIO2_PIN                  PA14  //
Add comment for Bluetooth switcher please!

2023-11-22 11:45 UTC, lida2003 requested changes

2023-11-22 11:45 UTC, lida2003 commented on src/main/target/AOCODARCF4V3/target.h
> +#define PINIO2_PIN                  PA14  //
Add comment for Bluetooth switcher, like VTX power switcher, please!

2023-11-22 11:45 UTC, lida2003 commented on src/main/target/AOCODARCF4V3/target.h
> +#define SERIALRX_PROVIDER               SERIALRX_SBUS
We use SERIALRX_CRSF for default settings. That's used for our PNP 7 inch copters.

2023-11-23 09:35 UTC, 634296207 commented
1.Add Bluetooth comment
2.Use the crsf protocol
2.Turn on the led light belt function

2023-12-09 23:57 UTC, lida2003 commented
Default settings, please keep consistent with https://github.com/Aocoda-RC/unified-targets/pull/2

2023-12-13 01:20 UTC, 634296207 commented
> Default settings, please keep consistent with [Aocoda-RC/unified-targets#2](https://github.com/Aocoda-RC/unified-targets/pull/2）
I looked at someone else's code and couldn't find the Settings for dsoht600

2023-12-13 01:21 UTC, 634296207 commented
I looked at someone else's code and couldn't find the Settings for dsoht600

2023-12-13 02:54 UTC, lida2003 commented
Can you cleanup the PR, as there are quite a lot of irrelevant commits?

2023-12-13 03:53 UTC, closed without merging